In [36]:
import os
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [25]:
dir = os.getcwd()
credit_card_df = pd.read_csv('../data/creditcard.csv')

duplicate_values = credit_card_df.duplicated()

credit_card_df = credit_card_df.drop_duplicates()

In [26]:
X =credit_card_df[['V14','V10','V20','V12','V7', 'V13','V4','V15']]
y = credit_card_df['Class']

In [50]:
sm = SMOTE(sampling_strategy=0.08)

In [32]:
#Logistic Regression
model = LogisticRegression(max_iter=1000)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.3,0.4,0.5,0.6,0.7,0.8,0.9]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.3        0.261752     0.864681  0.401542
1        0.4        0.374963     0.847727  0.519613
2        0.5        0.481015     0.843494  0.611998
3        0.6        0.571234     0.841389  0.679760
4        0.7        0.656199     0.828667  0.731829
5        0.8        0.705644     0.811758  0.754185
6        0.9        0.755965     0.788511  0.771559

In [38]:
#DecisionTreeClassifier_01
model = DecisionTreeClassifier(max_depth=10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.3,0.4,0.5,0.6,0.7,0.8,0.9]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        



        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.3        0.216438     0.820246  0.341299
1        0.4        0.283173     0.803315  0.416914
2        0.5        0.324632     0.803292  0.461974
3        0.6        0.402566     0.780022  0.529598
4        0.7        0.561511     0.796976  0.657239
5        0.8        0.596205     0.790571  0.678811
6        0.9        0.734631     0.771557  0.752265

In [37]:
#KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.3,0.4,0.5,0.6,0.7,0.8,0.9]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        



        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.3        0.199404     0.852004  0.322948
1        0.4        0.248648     0.849877  0.384521
2        0.5        0.302348     0.845644  0.445159
3        0.6        0.362138     0.845644  0.506665
4        0.7        0.428337     0.835028  0.565818
5        0.8        0.527965     0.828690  0.644348
6        0.9        0.639871     0.818096  0.717202

In [40]:
#RandomForestClassifier_01
model = RandomForestClassifier(max_depth=10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.3,0.4,0.5,0.6,0.7,0.8,0.9]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        



        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.3        0.573233     0.851982  0.682861
1        0.4        0.708161     0.830817  0.763338
2        0.5        0.775006     0.815991  0.793430
3        0.6        0.840950     0.801165  0.819148
4        0.7        0.872598     0.771467  0.818047
5        0.8        0.919011     0.748152  0.823289
6        0.9        0.939356     0.703830  0.803674

In [42]:
#RandomForestClassifier_02
model = RandomForestClassifier(max_depth= 5,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.757728     0.822329  0.788393
1        0.6        0.808287     0.807525  0.807661

In [43]:
#RandomForestClassifier_03
#oooooooooooooooooooooooooooooooooooooooooooooooooooooo
model = RandomForestClassifier(max_depth= 6,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.753951     0.830817  0.790070
1        0.6        0.803772     0.809653  0.806017

In [80]:
#Logistic Regression
#leaf = 9 0.78 /0.82 ooooooooooooooooooooooooooooooooooooooooooooo
#leaf =6  0.75 / 0.82
#leaf =10  noppppp

sm = SMOTE(sampling_strategy=0.08)

model = RandomForestClassifier(max_depth= 7,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.5]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.767223     0.824457  0.794489

In [58]:
#Logistic Regression

sm = SMOTE(sampling_strategy=0.09)

model = RandomForestClassifier(max_depth= 7,max_leaf_nodes= 9)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.738702     0.828690  0.780880
1        0.6        0.798957     0.805353  0.801415

In [45]:
#Logistic Regression
model = RandomForestClassifier(max_depth= 8,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)

threshholds = [0.5,0.6,0.7]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.761130     0.826585  0.792315
1        0.6        0.807759     0.803359  0.805311
2        0.7        0.842713     0.775812  0.807539

In [82]:
#Logistic Regression
#8 -->0.77 /0.82
#10-->0.77 /0.826
model = RandomForestClassifier(max_depth= 6,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.06)

threshholds = [0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.774696     0.826585  0.799649
1        0.6        0.831820     0.788488  0.808515

In [79]:
#Logistic Regression
#leaf0.08 no 0.76 /0.81
#lesf 9 -> 0.76/0.82
#leaf 10 -> 0.75/0.82
model = RandomForestClassifier(max_depth= 6,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.08)

threshholds = [0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.754826     0.826562  0.788535
1        0.6        0.794749     0.809675  0.801509

In [70]:
#Logistic Regression
#L=0.7
#leaf0 8 good 0.77 /0.82
#leaf 7 0.78/0.81
# leaf 9 0.76 /0.81
model = RandomForestClassifier(max_depth= 6,max_leaf_nodes= 8)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.075)

threshholds = [0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.778895     0.820202  0.798600
1        0.6        0.827201     0.790683  0.807964

In [81]:
#Logistic Regression

#0.5 0.75 /0.82
# 0.09 -> leaf 10 _> 0.77 /0.82 / best
# 0.09 -> leaf 9_>nope
# 0.09 -> leaf 11_>0.74 / 0.83
#0.09 -> leaf 7 -> nope


#st 0.85 leaf 10 --> no
model = RandomForestClassifier(max_depth= 6,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.085)

threshholds = [0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.5        0.751018     0.826562  0.786610
1        0.6        0.803505     0.809653  0.805894

In [ ]:
#Logistic Regression

#10-->?
model = RandomForestClassifier(max_depth= 7,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.06)

threshholds = [0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df