In [2]:
import os
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [3]:
dir = os.getcwd()
credit_card_df = pd.read_csv('../data/creditcard.csv')

duplicate_values = credit_card_df.duplicated()

credit_card_df = credit_card_df.drop_duplicates()

In [4]:
X =credit_card_df[ ['V14', 'V17', 'V10', 'V12', 'V4', 'V28', 'V26', 'V27', 'Time', 'V7', 'V20', 'V8', 'V9', 'V25', 'V1', 'V6', 'V22', 'V18', 'V21', 'V2']]
y = credit_card_df['Class']

In [6]:

model = RandomForestClassifier(max_depth= 5,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.06)

threshholds = [0.3,0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.3        0.700471     0.839261  0.763430
1        0.5        0.762556     0.828690  0.793959
2        0.6        0.808807     0.811803  0.809721

In [7]:

model = RandomForestClassifier(max_depth= 5,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.1)

threshholds = [0.3,0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.3        0.647531     0.841389  0.731568
1        0.5        0.741482     0.830840  0.783215
2        0.6        0.793746     0.822352  0.806969

In [8]:

model = RandomForestClassifier(max_depth= 7,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.06)

threshholds = [0.3,0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.3        0.693325     0.839261  0.759100
1        0.5        0.757077     0.830795  0.791940
2        0.6        0.813267     0.816013  0.814017

In [9]:

model = RandomForestClassifier(max_depth= 7,max_leaf_nodes= 10)
cv = StratifiedKFold(
    n_splits= 5 ,
    shuffle= True,
    random_state= 42,
)
#0.07
sm = SMOTE(sampling_strategy=0.1)

threshholds = [0.3,0.5,0.6]

results =[]
for threshold in threshholds:
    precision_scores = []
    recall_scores = []
    f1_scores = []
    for train_idx, test_idx in cv.split(X,y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]
        
        pipeline = Pipeline([
            ('scale' ,StandardScaler()),
            ('sm' , sm),
            ('model' , model)
            
        ])
        pipeline.fit(X_train,y_train)
        proba = pipeline.predict_proba(X_test)[:,1]

        
        y_pred = (proba >= threshold).astype(int)
        
        p_score =precision_score(y_test,y_pred)
        precision_scores.append(p_score)
        
        r_score = recall_score(y_test,y_pred)
        recall_scores.append(r_score)
        
        f_one_score = f1_score(y_test,y_pred)
        f1_scores.append(f_one_score)
        
        
    result ={ 
        'Threshold': threshold,
        'Mean Precision': np.mean(precision_scores),
        'Mean Recall': np.mean(recall_scores),
        'Mean F1': np.mean(f1_scores)
        }
        
    results.append(result)


result_df = pd.DataFrame(results)

result_df

   Threshold  Mean Precision  Mean Recall   Mean F1
0        0.3        0.643625     0.841389  0.729055
1        0.5        0.741639     0.835050  0.785415
2        0.6        0.788814     0.824479  0.805512